"""Generate the PostgreSQL schema from the real raw-data columns.

Run from the repository root:

    python db/make_schema.py

The generated db/init.sql contains schema definitions only.
No sensor values are written to the SQL file.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.data import TEST_RUN, list_runs, load_run


runs = list_runs()

development_runs = sorted(
    run_name
    for run_name in runs
    if run_name != TEST_RUN
)

if not development_runs:
    raise RuntimeError("No development runs were found.")

example_run = development_runs[0]
df = load_run(runs[example_run])

sensor_columns = [
    column
    for column in df.columns
    if column not in ("timestamp", "label")
]

if len(sensor_columns) != 90:
    raise RuntimeError(
        f"Expected 90 sensor columns, found {len(sensor_columns)}."
    )

sql_sensor_columns = [
    column.lower()
    for column in sensor_columns
]

if len(set(sql_sensor_columns)) != len(sql_sensor_columns):
    raise RuntimeError(
        "Sensor column names collide after lowercasing."
    )

for column in sql_sensor_columns:
    if not re.fullmatch(r"[a-z][a-z0-9_]*", column):
        raise RuntimeError(
            f"Unsafe SQL column name: {column!r}"
        )

sensor_ddl = ",\n".join(
    f"    {column} DOUBLE PRECISION"
    for column in sql_sensor_columns
)

ddl = f"""-- Generated by db/make_schema.py.
-- Sensor timestamps in the source files have no verified timezone,
-- so they are stored as TIMESTAMP WITHOUT TIME ZONE.

CREATE TABLE IF NOT EXISTS runs (
    run_id TEXT PRIMARY KEY,
    split TEXT NOT NULL
        CHECK (split IN ('development', 'test')),
    source_file TEXT NOT NULL,
    n_rows INTEGER NOT NULL CHECK (n_rows > 0),
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (ended_at >= started_at)
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    run_id TEXT NOT NULL
        REFERENCES runs(run_id)
        ON DELETE CASCADE,

    row_idx INTEGER NOT NULL
        CHECK (row_idx >= 0),

    ts TIMESTAMP NOT NULL,

    sampling_label SMALLINT NOT NULL
        CHECK (sampling_label BETWEEN 1 AND 6),

{sensor_ddl},

    PRIMARY KEY (run_id, row_idx)
);

CREATE UNIQUE INDEX IF NOT EXISTS sensor_readings_run_ts_idx
    ON sensor_readings (run_id, ts);

CREATE INDEX IF NOT EXISTS sensor_readings_ts_idx
    ON sensor_readings (ts);

CREATE TABLE IF NOT EXISTS forecast_log (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    run_id TEXT NOT NULL
        REFERENCES runs(run_id)
        ON DELETE CASCADE,

    origin_row INTEGER NOT NULL
        CHECK (origin_row >= 0),

    target_row INTEGER NOT NULL
        CHECK (target_row >= 0),

    context_steps SMALLINT NOT NULL
        CHECK (context_steps > 0),

    horizon_steps SMALLINT NOT NULL
        CHECK (horizon_steps > 0),

    model_version TEXT NOT NULL,

    selected_epoch INTEGER NOT NULL
        CHECK (selected_epoch >= 0),

    forecast JSONB NOT NULL,
    persistence JSONB NOT NULL,
    correction JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS forecast_log_run_origin_idx
    ON forecast_log (run_id, origin_row);
"""

output_path = ROOT / "db" / "init.sql"
output_path.write_text(ddl, encoding="utf-8")

print(
    f"Wrote {output_path.relative_to(ROOT)} "
    f"with {len(sql_sensor_columns)} sensor columns."
)
print(f"Schema source run: {example_run}")
